name: Deploy docker images to DigitalOcean Container Registry

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: Push docker image to DigitalOcean Container Registry
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "3.1"
          - "3.0"
          - "2.7"
    steps:
      - 
        name: Checking out the repository
        uses: actions/checkout@v2
      - 
        name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1
      - 
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCR_PAT }}
      - 
        name: Login to Container Registry
        run: doctl registry login -t ${{ secrets.DOCR_PAT }}
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            RUBY_BUILD_VERSION=${{ matrix.tag }}
          context: ./build
          push: true
          tags: |
            registry.digitalocean.com/${{ secrets.DOCR_ORG }}/ruby:${{ matrix.tag }}
