name:  Deploy docker images to multiple registries

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - stable

jobs:
  push_to_registry:
    name: Push Docker image
    continue-on-error: ${{ matrix.experimental }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        tag:
          - "3.0"
          - "2.7"
        include:
          - tag: "latest"
            experimental: true
          - tag: "3.1"
            experimental: true
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Log in to the GitHub Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - 
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCR_PAT }}
      - 
        name: Login to Digital Ocean Container Registry
        run: doctl registry login -t ${{ secrets.DOCR_PAT }}
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            RUBY_BUILD_VERSION=${{ matrix.tag }}
          context: ./build
          push: true
          tags: |
            tenshiamd/ruby:${{ matrix.tag }}
            ghcr.io/tenshiamd/ruby:${{ matrix.tag }}
            registry.digitalocean.com/${{ secrets.DOCR_ORG }}/ruby:${{ matrix.tag }}
