name: Deploy docker images to DigitalOcean Container Registry

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: Push docker image to DigitalOcean Container Registry
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 2.7
    steps:
      - 
        name: Checking out the repository
        uses: actions/checkout@v2
      - 
        name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1
      - 
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DOCR_PAT }}
      - 
        name: Login to Container Registry
        run: doctl registry login -t ${{ secrets.DOCR_PAT }}
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          context: ./${{ matrix.tag }}
          tags: registry.digitalocean.com/${{ secrets.DOCR_ORG }}/ruby:${{ matrix.tag }}
