name: Deploy docker images to Docker Hub

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 2.7
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            RUBY_BUILD_VERSION=${{ matrix.tag }}
          context: ./build
          push: true
          tags: |
            tenshiamd/ruby:${{ matrix.tag }}
