name: Deploy images to DigitalOcean Container Registry

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: Push docker image to DigitalOcean Container Registry
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 2.7
          - 2.6
          - 2.5
    steps:
      - 
        name: Checking out the repository
        uses: actions/checkout@v2
      - 
        name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1
      - 
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.CR_PAT }}
      - 
        name: Login to Container Registry
        run: doctl registry login -t ${{ secrets.CR_PAT }}
      - 
        name: Build docker image
        run: cd ${{ matrix.tag }} && docker build -t registry.digitalocean.com/${{ secrets.CR_ORG }}/ruby:${{ matrix.tag }} .
      - 
        name: Push docker image
        run: docker push registry.digitalocean.com/${{ secrets.CR_ORG }}/ruby:${{ matrix.tag }}
