name: Update copyright year(s) in license file

on:
  schedule:
    - cron: "1 14 1 1 *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: FantasticFiasco/action-update-license-year@v1
